name: Main CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      - name: docker
        image: docker:20.10.9
        ports:
          - 80:80
          - 443:443

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: docker build -t my-docker-image .

      - name: Run Tests with Docker
        run: docker run my-docker-image ./gradlew test
