name: Main CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Use Node.js 16
        uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: |
          docker build -t my-docker-image .

      - name: Make Gradlew Executable
        run: |
          chmod +x ./gradlew

      - name: Run Tests with Docker
        run: |
          docker run my-docker-image ./gradlew test
